### ISSUE TITLE
Add a --dry-run flag

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/farmit#1]
## Tasks
+ [x] add --dry-run flag
+ ~~force --verbose when --dry-run is called~~
+ [x] do not commit, update file or create branch on --dry-run
(These should also happen with Verbose)
+ [x] output the file update text
+ ~~output the commit message text that would be used~~
+ ~~output the update the branch name that would be created~~

Update: Deferring some of these planned tasks for future consideration. `--dry-run` implementation in #19 meets the core needs without complicating the existing code.
