### ISSUE TITLE
Complete our Open Source checklist

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/farmit#6]
https://wiki.illinois.edu/wiki/display/SEC/Cybersecurity+Development+-+Open+Source+Checklist

## Tasks
+ [x] Do we expect Open Sourcing this solution to provide value to other members of the Academic / Security Community? Yes.
+ [x] Do we expect campus IT professionals to adopt this through a shared public repository? Yes. We intend to use this through PyPI.
+ [x] An acceptable open source license has been applied. 
+ Support expectations are added to the repository.
+ [x] ReadMe.md includes a statement that only best effort support is provided.
+ [x] An End of life date is included at the top of ReadMe.md, and is more than 6 months in the future. https://answers.uillinois.edu/illinois/109544
+ [x] A SECURITY.md file commits to providing security patches only for the latest major release and includes how to contact our Cybersecurity team.
+ [x] Consider and commit to relevant practices put forth in the Cybersecurity Example Development Standards
+ [x] At minimum, maintain a CHANGELOG.md file.
+ [x] Review the repository permissions (branches, pushes, pull requests, etc.)
+ [x] Team Manager has approved releasing this product as open source.
Discuss any planned variations from the above defaults with your manager.
+ [x] rename primary branch to `main`
+ [x] merge these updates to `main` branch.

**Comment by mpitcel** [comment]
We do have a KB article with EOL language FYI

**Comment by edthedev** [comment]
For review the repository permissions (branches, pushes, pull requests, etc.), we have an effort here to work toward a new knowledge base article with our team's recommended settings:
https://github.com/techservicesillinois/secdev-job-aids/issues/159

**Comment by edthedev** [comment]
We do have a job aid that covers our preferred branch rules, now.

**Comment by edthedev** [comment]
This was waiting on documenting our internal branch rules, which are close enough to ready that we can proceed.
